export const PostImages = {};

export const InstaIcons = {
  instaIcon: "/mediaFiles/icons/instagramLogo.svg",
  homeIcon: "/mediaFiles/icons/homepage.svg",
  homeFilledIcon: "/mediaFiles/icons/homepageFilled.svg",
  searchIcon: "/mediaFiles/icons/search.svg",
  searchFilledIcon: "/mediaFiles/icons/searchFilled.svg",
  navigateIcon: "/mediaFiles/icons/navigate.svg",
  navigateFilledIcon: "/mediaFiles/icons/navigateFilled.svg",
  reelsIcon: "/mediaFiles/icons/reels.svg",
  messageIcon: "/mediaFiles/icons/messenger.svg",
  messageFilledIcon: "/mediaFiles/icons/messengerFilled.svg",
  heartIcon: "/mediaFiles/icons/heart.svg",
  heartBlackFilledIcon: "/mediaFiles/icons/heartFilled2.svg",
  heartRedFilledIcon: "/mediaFiles/icons/heartFilled.svg",
  postIcon: "/mediaFiles/icons/addStory.svg",
  postFilledIcon: "/mediaFiles/icons/addStoryFilled.svg",
};

let x = {};
for (let i = 0; i < 20; i++) {
  x[`user${i}`] = `/mediaFiles/images/profileImages/${i}.png`;
}
export let ProfileImages = x;

export const GeneralImages = {
  instaTextImg: "/mediaFiles/images/instagramText.png",
};

export let suggestionBoxData = [
  {
    id: 1,
    username: "jhardesty0",
    name: "Justine Hardesty",
    followNotify: "Follow you",
    profileImage: "http://dummyimage.com/50x50.png/dddddd/000000",
    followStatus: true,
  },
  {
    id: 2,
    username: "aillingworth1",
    name: "Alyse Illingworth",
    followNotify: "Follow by +1",
    profileImage: "http://dummyimage.com/50x50.png/ff4444/ffffff",
    followStatus: true,
  },
  {
    id: 3,
    username: "leverist2",
    name: "Lisabeth Everist",
    followNotify: "Follow you",
    profileImage: "http://dummyimage.com/50x50.png/5fa2dd/ffffff",
    followStatus: false,
  },
  {
    id: 4,
    username: "jbarff3",
    name: "Janeva Barff",
    followNotify: "Follow by +2 more..",
    profileImage: "http://dummyimage.com/50x50.png/ff4444/ffffff",
    followStatus: false,
  },
  {
    id: 5,
    username: "tpaffett4",
    name: "Thadeus Paffett",
    followNotify: "Follow by +2 more..",
    profileImage: "http://dummyimage.com/50x50.png/cc0000/ffffff",
    followStatus: false,
  },
  {
    id: 6,
    username: "oingleson5",
    name: "Osborn Ingleson",
    followNotify: "New to Instagram",
    profileImage: "http://dummyimage.com/50x50.png/cc0000/ffffff",
    followStatus: true,
  },
  {
    id: 7,
    username: "lmulrean6",
    name: "Lyndsie Mulrean",
    followNotify: "Follow by +2 more..",
    profileImage: "http://dummyimage.com/50x50.png/5fa2dd/ffffff",
    followStatus: false,
  },
  {
    id: 8,
    username: "mstorrier7",
    name: "Milzie Storrier",
    followNotify: "Follow by +5 more..",
    profileImage: "http://dummyimage.com/50x50.png/ff4444/ffffff",
    followStatus: false,
  },
  {
    id: 9,
    username: "svaadeland8",
    name: "Sol Vaadeland",
    followNotify: "Follow by +1",
    profileImage: "http://dummyimage.com/50x50.png/cc0000/ffffff",
    followStatus: false,
  },
  {
    id: 10,
    username: "aharston9",
    name: "Arlene Harston",
    followNotify: "Follow by +5 more..",
    profileImage: "http://dummyimage.com/50x50.png/dddddd/000000",
    followStatus: false,
  },
  {
    id: 11,
    username: "mlaitya",
    name: "Murial Laity",
    followNotify: "Follow by +5 more..",
    profileImage: "http://dummyimage.com/50x50.png/dddddd/000000",
    followStatus: false,
  },
  {
    id: 12,
    username: "vgriffithsb",
    name: "Victoria Griffiths",
    followNotify: "New to Instagram",
    profileImage: "http://dummyimage.com/50x50.png/dddddd/000000",
    followStatus: false,
  },
  {
    id: 13,
    username: "dbroganc",
    name: "Danny Brogan",
    followNotify: "Follow by +1",
    profileImage: "http://dummyimage.com/50x50.png/ff4444/ffffff",
    followStatus: false,
  },
  {
    id: 14,
    username: "wgoldthorpd",
    name: "Wilhelmina Goldthorp",
    followNotify: "New to Instagram",
    profileImage: "http://dummyimage.com/50x50.png/cc0000/ffffff",
    followStatus: true,
  },
  {
    id: 15,
    username: "nricarde",
    name: "Nerte Ricard",
    followNotify: "Follow by +5 more..",
    profileImage: "http://dummyimage.com/50x50.png/cc0000/ffffff",
    followStatus: false,
  },
  {
    id: 16,
    username: "hjurgensonf",
    name: "Henri Jurgenson",
    followNotify: "Follow by +2 more..",
    profileImage: "http://dummyimage.com/50x50.png/dddddd/000000",
    followStatus: true,
  },
  {
    id: 17,
    username: "mliverockg",
    name: "Mariquilla Liverock",
    followNotify: "Follow by +5 more..",
    profileImage: "http://dummyimage.com/50x50.png/5fa2dd/ffffff",
    followStatus: true,
  },
  {
    id: 18,
    username: "ciozefovichh",
    name: "Cyndy Iozefovich",
    followNotify: "Follow by +1",
    profileImage: "http://dummyimage.com/50x50.png/cc0000/ffffff",
    followStatus: true,
  },
  {
    id: 19,
    username: "hmccreeryi",
    name: "Huberto McCreery",
    followNotify: "Follow by +1",
    profileImage: "http://dummyimage.com/50x50.png/cc0000/ffffff",
    followStatus: true,
  },
  {
    id: 20,
    username: "eramblej",
    name: "Edith Ramble",
    followNotify: "Follow by +5 more..",
    profileImage: "http://dummyimage.com/50x50.png/dddddd/000000",
    followStatus: true,
  },
];

let postFeedData = [
  {
    id: 1,
    profileImage: "",
    username: "mmcgrirl0",
    postedTime: "2023-07-16T04:34:22Z",
    isFollowed: false,
    description: "Lost in wanderlust",
    caption: "Chasing dreams",
    isLiked: "",
    isSaved: "",
    postedImage: "",
    posts: 563,
    followers: 1513,
    following: 5618,
  },
  {
    id: 2,
    profileImage: "",
    username: "epowland1",
    postedTime: "2023-07-16T09:34:04Z",
    isFollowed: false,
    description: "Exploring new horizons",
    caption: "Squad goals",
    isLiked: "",
    isSaved: "",
    postedImage: "",
    posts: 74,
    followers: 1512,
    following: 6076,
  },
  {
    id: 3,
    profileImage: "",
    username: "kgardner2",
    postedTime: "2023-07-16T23:41:14Z",
    isFollowed: false,
    description: "Making memories",
    caption: "Making memories",
    isLiked: "",
    isSaved: "",
    postedImage: "",
    posts: 88,
    followers: 7989,
    following: 9053,
  },
  {
    id: 4,
    profileImage: "",
    username: "rlangton3",
    postedTime: "2023-07-16T21:55:32Z",
    isFollowed: true,
    description: "Chasing dreams",
    caption: "Chasing dreams",
    isLiked: "",
    isSaved: "",
    postedImage: "",
    posts: 659,
    followers: 3054,
    following: 5486,
  },
  {
    id: 5,
    profileImage: "",
    username: "dbycraft4",
    postedTime: "2023-07-17T03:18:38Z",
    isFollowed: true,
    description: "Finding joy in everyday moments",
    caption: "Living my best life!",
    isLiked: "",
    isSaved: "",
    postedImage: "",
    posts: 352,
    followers: 2579,
    following: 3256,
  },
  {
    id: 6,
    profileImage: "",
    username: "satcheson5",
    postedTime: "2023-07-16T10:20:15Z",
    isFollowed: false,
    description: "Celebrating life",
    caption: "Good vibes only",
    isLiked: "",
    isSaved: "",
    postedImage: "",
    posts: 636,
    followers: 4292,
    following: 1265,
  },
  {
    id: 7,
    profileImage: "",
    username: "jhoble6",
    postedTime: "2023-07-16T16:11:00Z",
    isFollowed: true,
    description: "Coffee and contemplation",
    caption: "moon child",
    isLiked: "",
    isSaved: "",
    postedImage: "",
    posts: 402,
    followers: 7874,
    following: 1652,
  },
  {
    id: 8,
    profileImage: "",
    username: "mgettone7",
    postedTime: "2023-07-16T10:18:35Z",
    isFollowed: false,
    description: "Life is better at the beach",
    caption: "Beach days and bonfires",
    isLiked: "",
    isSaved: "",
    postedImage: "",
    posts: 556,
    followers: 3554,
    following: 4401,
  },
  {
    id: 9,
    profileImage: "",
    username: "dfenny8",
    postedTime: "2023-07-16T22:34:13Z",
    isFollowed: true,
    description: "Embracing self-love",
    caption: "Living my best life!",
    isLiked: "",
    isSaved: "",
    postedImage: "",
    posts: 266,
    followers: 2390,
    following: 9413,
  },
  {
    id: 10,
    profileImage: "",
    username: "jjoysey9",
    postedTime: "2023-07-17T03:42:08Z",
    isFollowed: false,
    description: "Spreading positivity",
    caption: "Beach days and bonfires",
    isLiked: "",
    isSaved: "",
    postedImage: "",
    posts: 30,
    followers: 1146,
    following: 8062,
  },
  {
    id: 11,
    profileImage: "",
    username: "hslattena",
    postedTime: "2023-07-16T05:10:42Z",
    isFollowed: true,
    description: "Creating my own sunshine",
    caption: "Adventure awaits",
    isLiked: "",
    isSaved: "",
    postedImage: "",
    posts: 121,
    followers: 3291,
    following: 675,
  },
  {
    id: 12,
    profileImage: "",
    username: "rjeannessonb",
    postedTime: "2023-07-16T01:36:48Z",
    isFollowed: true,
    description: "Weekend adventures",
    caption: "Good vibes only",
    isLiked: "",
    isSaved: "",
    postedImage: "",
    posts: 229,
    followers: 7619,
    following: 1212,
  },
  {
    id: 13,
    profileImage: "",
    username: "bbridgec",
    postedTime: "2023-07-17T13:24:23Z",
    isFollowed: false,
    description: "Embracing self-love",
    caption: "moon child",
    isLiked: "",
    isSaved: "",
    postedImage: "",
    posts: 274,
    followers: 2664,
    following: 4165,
  },
  {
    id: 14,
    profileImage: "",
    username: "mgerhardtd",
    postedTime: "2023-07-16T04:17:45Z",
    isFollowed: false,
    description: "Sunset vibes",
    caption: "Making memories",
    isLiked: "",
    isSaved: "",
    postedImage: "",
    posts: 85,
    followers: 1803,
    following: 7121,
  },
  {
    id: 15,
    profileImage: "",
    username: "tcobdene",
    postedTime: "2023-07-16T16:18:59Z",
    isFollowed: true,
    description: "Savoring the little things",
    caption: "Beach days and bonfires",
    isLiked: "",
    isSaved: "",
    postedImage: "",
    posts: 24,
    followers: 1286,
    following: 4121,
  },
  {
    id: 16,
    profileImage: "",
    username: "cairdf",
    postedTime: "2023-07-17T16:34:13Z",
    isFollowed: true,
    description: "Creating my own sunshine",
    caption: "Sunsets and palm trees",
    isLiked: "",
    isSaved: "",
    postedImage: "",
    posts: 51,
    followers: 2914,
    following: 3076,
  },
  {
    id: 17,
    profileImage: "",
    username: "tdrewsg",
    postedTime: "2023-07-16T03:26:48Z",
    isFollowed: true,
    description: "Savoring the little things",
    caption: "Happiness is homemade",
    isLiked: "",
    isSaved: "",
    postedImage: "",
    posts: 256,
    followers: 4840,
    following: 6718,
  },
  {
    id: 18,
    profileImage: "",
    username: "cvannaccih",
    postedTime: "2023-07-17T07:03:45Z",
    isFollowed: true,
    description: "Coffee and contemplation",
    caption: "Sunsets and palm trees",
    isLiked: "",
    isSaved: "",
    postedImage: "",
    posts: 587,
    followers: 9908,
    following: 1744,
  },
  {
    id: 19,
    profileImage: "",
    username: "ashilvocki",
    postedTime: "2023-07-16T14:58:29Z",
    isFollowed: false,
    description: "Exploring new horizons",
    caption: "Making memories",
    isLiked: "",
    isSaved: "",
    postedImage: "",
    posts: 70,
    followers: 1202,
    following: 3410,
  },
  {
    id: 20,
    profileImage: "",
    username: "tjudgkinsj",
    postedTime: "2023-07-17T05:18:56Z",
    isFollowed: true,
    description: "Living in the moment",
    caption: "Living my best life!",
    isLiked: "",
    isSaved: "",
    postedImage: "",
    posts: 232,
    followers: 4034,
    following: 1854,
  },
  {
    id: 21,
    profileImage: "",
    username: "kmattingleyk",
    postedTime: "2023-07-16T16:46:16Z",
    isFollowed: false,
    description: "Life is better at the beach",
    caption: "Good vibes only",
    isLiked: "",
    isSaved: "",
    postedImage: "",
    posts: 388,
    followers: 1134,
    following: 8889,
  },
];
export let InstaPostData = postFeedData.map((i, idx) => {
  i.profileImage = `/mediaFiles/images/profileImages/${idx}.png`;
  i.postedImage = `/mediaFiles/images/postImages/${idx + 1}.png`;
  i.isLiked = false;
  i.isSaved = false;
  return i;
});
